Use CDN instead of physical files
primait/pyxis-scss pull request #13
Opened 2021-11-04 14:34 UTC by alessiosantangelo

2021-11-04 14:58 UTC, lauratrapani approved these changes
LGTM

2021-11-04 15:08 UTC, emanuelemacri requested changes
Un paio di cosette

2021-11-04 15:08 UTC, emanuelemacri commented on src/scss/foundations/typography/index.scss
>    fallback: #{"Arial",
Tutto ok, sistemi solo questo a capo brutto? Dovrebbe essere:
`fallback: #{"Arial",  sans-serif},`

2021-11-04 15:08 UTC, emanuelemacri commented on src/scss/foundations/typography/index.scss
> +/// @access private
Domanda: mettiamo sempre uno spazio tra la descrizione e le varie keys?

```suggestion
/// The font path
///
/// @type String
/// @access private
```

2021-11-05 08:48 UTC, emanuelemacri approved these changes

2021-11-05 08:53 UTC, merged