[PRIMA-11714]: [Pyxis Scss] Aggiornare documentazione
primait/pyxis-scss pull request #15
Opened 2021-11-10 09:57 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-11714

Documentation for public variables, mixin and functions.

2021-11-10 11:50 UTC, lauratrapani commented on src/scss/foundations/colors.scss
> +/// @alias createAtoms
`@alias` è stato aggiunto per nascondere gli elementi dalla doc senza cambiarne l'accesso

2021-11-10 12:20 UTC, emanuelemacri requested changes
Ti ho messo un commento su quelle variabili vuote usate per visualizzare le prop delle varie mappe. Per il resto mi sembra ok, ma devo ancora leggermi tutto per bene su sassdoc

2021-11-10 12:20 UTC, emanuelemacri commented on src/scss/foundations/breakpoints.scss
> +$breakpoints: ();
Su sassodc è molto comodo avere questa mappa con le prop esposte, ma eviterei di avere una variabile pubblica, potremmo modificare in qualcosa tipo:

```suggestion
/// The breakpoints of Pyxis.
/// @hidden This variable is useful only in sassdoc documentation
///
/// @type Map
/// @prop {Number} base [1px]
/// @prop {Number} xxsmall [375px]
/// @prop {Number} xsmall [576px]
/// @prop {Number} small [768px]
/// @prop {Number} medium [992px]
/// @prop {Number} large [1200px]
/// @prop {Number} xlarge [1680px]
$_breakpointProps: ();
```

In questo modo non esponiamo la variabile, ma sassdoc continua comunque a renderizzarla correttamente (dato che non specifichiamo `@access`). Non è una soluzione meravigliosa, ma al momento non mi viene in mente nulla di meglio 🤔 

Farei questa modifica per tutte le variabili vuote con lo stesso pattern nei vari file (`$colors`, `$spacings`, ecc...)

2021-11-11 09:00 UTC, emanuelemacri requested changes
Un altro paio di cosette dopo aver visto la build di sassdoc

2021-11-11 09:52 UTC, lauratrapani commented on src/scss/foundations/breakpoints.scss
> +/// @ignore This variable is useful only in sassdoc documentation
Di comune accordo abbiamo deciso di cambiare la frase in "The variable is private.", con eventuale rimando alle funzioni sotto per recuperare i valori all'interno della mappa.

2021-11-11 09:53 UTC, lauratrapani commented on src/scss/foundations/elevations.scss
> +///     @include elevation(s, brand15);
Per uniformità abbiamo deciso di non mostrare l'output su nessun mixin

2021-11-11 09:53 UTC, lauratrapani commented on src/scss/lib/_map.scss
> +///
Aggiunto

2021-11-11 09:54 UTC, lauratrapani commented on src/scss/foundations/spacings.scss
> +///     @include padding(xl);
Il valore del parametro è stato uniformato, mentre è stato deciso per uniformità di non mettere l'output in nessun esempio nei mixins

2021-11-11 09:54 UTC, emanuelemacri approved these changes
LGTM 🚀

2021-11-11 10:29 UTC, alessiosantangelo approved these changes
LGTM

2021-11-11 10:30 UTC, merged